version: "3"

services:
  web:
    build: ./docker
    ports:
      - "8080:80"
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
    networks:
      - app_network
    restart: unless-stopped

  database:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: candoria
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - '8099:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '123456'
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - database

volumes:
  db-data:

networks:
  app_network:
