version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: candoria
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - 8080:80
    volumes:
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./public:/var/www/html/public  # Monte le dossier public de la racine du projet
      - ./:/var/www/html  # Monte l'ensemble du projet (tout ce qui est à la racine)
    depends_on:
      - database

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
###< doctrine/doctrine-bundle ###
